source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
def shared_pods
  pod 'JMMediaStackSDK', :path => '../../'
  #pod 'JMMediaStackSDK', :git => 'https://devops.jio.com/JioPlatforms/JioMeet_Pilot/_git/JMMediaSoup_iOS', :branch => 'master'
end

target 'MediaStack' do
  use_modular_headers!
  shared_pods
  target 'MediaStackScreenShare' do
    end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
    end
  end
end
