source 'https://github.com/CocoaPods/Specs.git'

target 'JMMediaSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JMMediaSampleApp

end

target 'JMMediaStackSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift', '~> 16.1.0'
  pod 'MMWormhole'
  pod 'VoiceActivityDetector'
  
  # LiveKit for dual WebRTC stack - LKRTC* classes
  pod 'LiveKit', '~> 2.0'
  # Pods for JMMediaStackSDK

end

post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'  # Updated for LiveKit compatibility
				config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
			end
		end
	end
end
