//
//  Models-Public+BroadcastMessage.swift
//  JMMediaStackSDK
//
//  Created by Onkar Dhanlobhe on 21/08/23.
//

import Foundation

public enum JMReactions: String, Codable, CaseIterable {
    case ThumbsUp = "ThumbsUp"
    case Clap = "Clap"
    case Heart = "Heart"
    case Celebration = "Celebration"
    case Smile = "Smile"
    case HeartEyes = "HeartEyes"
    case HighFive = "HighFive"
    case Sad = "Sad"
    case None = ""
}

// Define the message structure
public struct JMBroadcastMessage: Codable {
    let eventName: String
    let msgData: JMMessageData
    let peerId: String
    let timeStamp: TimeInterval
}

public struct JMMessageData: Codable {
    let message: String
    let reactionsType: JMReactions
    let sender: JMSender
    let targetParticipantId: String
    let type: String
}

public class JMSender: Codable {
    var name: String = ""
    var participantId: String = ""
    var userId: String = ""
    
    init(name: String, participantId: String, userId: String) {
        self.name = name
        self.participantId = participantId
        self.userId = userId
    }
    
    init(){}
}

public enum JMRTMMessagesType: String, Codable {
    case broadcastMessage
    case broadcastMessageToPeer
}

public enum JMRTMMessage: String,Codable {
    case HOST_IDENTITY = "HOSTURIEWBUBBWBWEFWEJBJKBBHJKJANRD@HOST_URI"
    case HOST_START_VIDEO = "ASDBSAHJDKDMNASBMASHWQEQWOECBEIWURGEWFBDSN@START"
    case HOST_STOP_VIDEO = "ASDBSAHJDKDMNASBMASHWQEQWOECBEIWURGEWFBDSN@STOP"
    case HOST_START_AUDIO = "CVXVFGRGKMWQEWQIEJUIIOIQWEJOIQWJEOIJQWIEJQ@START"
    case HOST_STOP_AUDIO = "CVXVFGRGKMWQEWQIEJUIIOIQWEJOIQWJEOIJQWIEJQ@STOP"
    case HOST_LOCK_ROOM = "ASFSDFASIJOIIKIJINBNMBLESIFJDBHHJRBMBNXXZC@LOCK"
    case HOST_UNLOCK_ROOM = "POIYGNSGJLEGTBSKDBPEBHFTEKSSALND@UNLOCK"
    case HOST_DISCONNECT_ALL,HOST_STOP_AUDIO_CALL,CONFERENCE_END_ALL = "QWEJKQKWEBKJCBXFCJDFKJSDSFDSFDSFDSFDS@ENDCALL"
    case HOST_START_RECORDING = "RECSTAHJDKDMNASBMASHWQEQWOECBEIWURGEWFBDSN@START"
    case HOST_STOP_RECORDING = "RECSTAHJDKDMNASBMASHWQEQWOECBEIWURGEWFBDSN@STOP"
    case HOST_START_CALL = "CONSTAHJDKDMNASBMASHWQEQWOECBEIWURGEWFBDSN@STARTCALL"
    case HOST_START_WHITEBOARD = "WHHEGUYGTUYGJHGBMABJIHJKJANRD@START_WHITEBOARD"
    case HOST_STOP_WHITEBOARD = "WHHEGUYGTUYGJHGBMABJIHJKJANRD@STOP_WHITEBOARD"
    case HOST_FORCE_HARD_MUTE = "SAGHKGHJAGJHGAYWTYDTDUY@FORCE_HARD_MUTE"
    case HOST_FORCE_HARD_UNMUTE = "SAGHKGHJAGJHGAYWTYDTDUY@FORCE_HARD_UNMUTE"
    case HOST_LOWER_HAND = "QSGXVGHSVXHSGVGVSDJHBSOUYIUY@HOST_LOWER_HAND"
    case HOST_LOWER_ALL_HANDS = "QSGXVGHSVXHSGVGVSDJHBSOUYIUY@LOWER_ALL_HANDS"
    case PARTICIPANT_START_VIDEO = "MOKMJBNJDCBDSNFBSDFMNDSBFNMASDEIWEHDSA@START"
    case PARTICIPANT_STOP_VIDEO = "MOKMJBNJDCBDSNFBSDFMNDSBFNMASDEIWEHDSA@STOP"
    case PARTICIPANT_START_AUDIO = "ZFDSRTTOERJJDFBNDJKSFBNDFMNSDBBGNAERQW@START"
    case PARTICIPANT_STOP_AUDIO = "ZFDSRTTOERJJDFBNDJKSFBNDFMNSDBBGNAERQW@STOP"
    case PARTICIPANT_DISCONNECT_CALL = "BODSRTTOERJJDFBNDJKSFBNDFMNSDBBGNBRYERQW@END"
    case PARTRICIPANT_START_SHARE = "KJHEGUYGTUYGJHGBMABJIHJKJANMB@START_SHARE"
    case PARTRICIPANT_STOP_SHARE,HOST_STOP_SHARE = "KJHEGUYGTUYGJHGBMABJIHJKJANMB@STOP_SHARE"
    case PARTICIPANT_HAND_RAISE = "QSGXVGHSVXHSGVGVSDJHBSOUYIUY@HAND_RAISE"
    case PARTICIPANT_COHOST_GRANT = "COHEGUYGTUYGJHGBMABJIHJKJANMB@COHOST_GRANT"
    case PARTICIPANT_COHOST_REVOKE = "COHEGUYGTUYGJHGBMABJIHJKJANMB@COHOST_REVOKE"
    case PARTICIPANT_BACKGROUND_ACTIVATED = "PARTICIPANT_BACKGROUND_ACTIVATED"
    case PARTICIPANT_BACKGROUND_INACTIVATED = "PARTICIPANT_BACKGROUND_INACTIVATED"
    case CONFERENCE_LOCKED = "ConferenceLocked"
    case CAMERA_MICROPHONE_PERMISSION = "Camera/Microphone access failed"
    case DISABLE_SPEAKER = "ASPJHJKHAXZQOWQEQWOECBEIWURGEWFBDSN_DISABLE_SPEAKER "
    case PARTICIPANT_REJECT_CAMERA_REQUEST = "ZFDSRTTOERJJDFBNDNDFMNSDBBG@VIDEO_DECLINE"
    case PARTICIPANT_REJECT_MIC_REQUEST = "ZFDSRTTOERJJDFBNDNDFMNSDBBG@MIC_DECLINE"
    case UPGRADE_AUDIENCE = "HOSTSTASDDAHJDKDMNASBMADASHWE@UPGRADE_AUDIENCE"
    case DOWNGRADE_AUDIENCE = "HOSTSTASDDAHJDKDMNASBMADASHW@DOWNGRADE_PARTICIPANT"
    case SEND_VC_PIN = "CAKASNKADNIHIHDAKNKAKDKSOWYURWGTWEBMHVB@DTMF"
    case REACTIONS = "PEERVGHSVXHSGVGPQRJHBSOUYSDQ@REACTION_SHARE"
    case NONE = ""
}

